### ISSUE TITLE
socketio.exceptions.ConnectionError: OPEN packet not returned by server

### ISSUE THREAD

**Issue by coandco** [Jille/karafun-fair-scheduler#4]
This seems to be broken.  Perhaps Karafun changed the remote socketio protocol?

```
$ python scheduler.py <roomcode>
Traceback (most recent call last):
  File "scheduler.py", line 104, in <module>
    sio.connect('https://www.karafun.com/?remote=kf%s' % args.channel)
  File "/home/<username>/.local/lib/python3.8/site-packages/socketio/client.py", line 284, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: OPEN packet not returned by server
```

**Comment by coandco** [comment]
I tried using this with Python 2.7, but the `python-socketio` package won't install any more.

```
$ python2 -m pip install --user python-socketio
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting python-socketio
  Using cached python_socketio-5.3.0-py2.py3-none-any.whl (53 kB)
Collecting python-engineio>=4.1.0
  Using cached python_engineio-4.2.0-py2.py3-none-any.whl (51 kB)
ERROR: Could not find a version that satisfies the requirement bidict>=0.21.0 (from python-socketio) (from versions: 0.1.5, 0.2.1, 0.3.0, 0.3.1, 0.9.0rc0, 0.9.0.post1, 0.10.0, 0.10.0.post1, 0.11.0, 0.12.0.post1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0.dev0, 0.15.0.dev1, 0.15.0rc1, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4)
ERROR: No matching distribution found for bidict>=0.21.0 (from python-socketio)
```

**Comment by coandco** [comment]
Fixed via the above pull request.  It turned out that the issue was twofold: one, Karafun had updated the URL from https://www.karafun.com/?remote=kf123456 to https://www.karafun.com/socket.io/?remote=kf123456.  Two, as you can see [here](https://github.com/miguelgrinberg/python-socketio), the latest versions of the python-socketio library use a newer version of the SocketIO/EngineIO protocol that's incompatible with what Karafun uses (version 3 of EngineIO).  By installing a 4.x.x version of python-socketio, it uses the correct protocol version and can successfully talk to Karafun.
