### ISSUE TITLE
keyerror: songid

### ISSUE THREAD

**Issue by Kickazz006** [Jille/karafun-fair-scheduler#6]
Latest Python
Karafun app running with proper id
Queue full of songs by many different users.
My original error was that requests didn't exist, so I installed that and tried again (yes, with a new powershell window)
Yes, I am running as administrator.

# pip install "python-socketio<5.0.0"
# pip install requests
# Karafun ID = xxxxxx
python scheduler.py xxxxxx

PS C:\Users\asdf\Documents\Personal\Karaoke> python scheduler.py <redacted #s>
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1394, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\asdf\Documents\Personal\Karaoke\scheduler.py", line 25, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Documents\Personal\Karaoke\scheduler.py", line 84, in handle
    action = qm.reconcile(data)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Documents\Personal\Karaoke\qmgr.py", line 30, in reconcile
    unseen = set(self.song2singer.keys()) - {s['songId'] for s in queue}
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Documents\Personal\Karaoke\qmgr.py", line 30, in <setcomp>
    unseen = set(self.song2singer.keys()) - {s['songId'] for s in queue}
                                             ~^^^^^^^^^^
KeyError: 'songId'

**Comment by Jille** [comment]
Hmm, they probably changed their protocol. Someone would have to dive in to figure out what they changed.

**Comment by Jille** [comment]
Which Karafun app are you using? The MacOS app doesn't expose the 'songid'.
Are you only queueing songs from their official catalog or also your own uploads?
